### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by RSRH-Rs** [qwerdvd/StarRailUID#1]
使用方法是直接把StarRailUID放到早柚核心的plugins文件夹里面吗，这边尝试了一下，并没有反应。

**Comment by qwerdvd** [comment]
来点日志

**Comment by RSRH-Rs** [comment]
![image](https://user-images.githubusercontent.com/54684882/235382747-6b7e3921-c4c7-4790-b8c2-a923a6311508.png)
看了一下日志，不知道为什么加载失败了，这边是使用的hoshinobot，需要把这个文件clone到hoshino的moduels文件夹下吗？
