### ISSUE TITLE
很多接口都1034了

### ISSUE THREAD

**Issue by mengluo04** [qwerdvd/StarRailUID#108]
比如深渊的，角色详情的，每日的，有什么解决办法吗

**Comment by qwerdvd** [comment]
可以上过码服务

**Comment by mengluo04** [comment]
> 可以上过码服务

不太懂怎么搞，可以说一下吗。1034之后没有其他的信息可以进行处理

**Comment by qwerdvd** [comment]
因为一些原因，不能提供这方面的支持

**Comment by qwerdvd** [comment]
anyway 929275476 可以来这里

**Comment by mengluo04** [comment]
> 因为一些原因，不能提供这方面的支持

好的

**Comment by mengluo04** [comment]
> 929275476

我是自用查数据，不是当群机器人

**Comment by qwerdvd** [comment]
有些东西可以进去问问，不太好放在这里2333

**Comment by mengluo04** [comment]
> 有些东西可以进去问问，不太好放在这里2333

有答案验证诶

**Comment by qwerdvd** [comment]
百度一下你就知道
