### ISSUE TITLE
启动的时候加载出错了

### ISSUE THREAD

**Issue by kokolikebanana** [qwerdvd/StarRailUID#11]
已经安装了mpmath了
![5DD78279-0654-42d9-BB9D-A1F13EFE7051](https://github.com/qwerdvd/StarRailUID/assets/49890746/9dc91466-7ad2-4f26-8533-a26bc4701ad0)

**Comment by KimigaiiWuyi** [comment]
没装，应该使用`poetry run pip install mpmath`安装

**Comment by kokolikebanana** [comment]
可以了，谢谢大佬，另外想问一下gsuid_core\data\StarRailUID\resource\char_icon 目录下为空，没有1101.png这个要怎么解决，要去哪里下载资源吗
![6E540A80-727F-47d5-8186-1766224998E3](https://github.com/qwerdvd/StarRailUID/assets/49890746/2c2dc947-5ed7-4669-a28d-578e9d2ddf88)

**Comment by qwerdvd** [comment]
资源可以去群里下载
sr面板结束之后 就会更新自动资源下载

**Comment by kokolikebanana** [comment]
大佬有群号吗，想加下群

**Comment by qwerdvd** [comment]
929275476
