### ISSUE TITLE
windows下载资源报错

### ISSUE THREAD

**Issue by touchscale** [qwerdvd/StarRailUID#110]
![image](https://github.com/qwerdvd/StarRailUID/assets/107158734/f2eb6aba-cf6c-4bc9-9cd8-fe16cb13675e)

**Comment by qwerdvd** [comment]
资源下载将会重构，并引入新的资源站
目前可以先去929275476下载资源包应急

**Comment by touchscale** [comment]
OK，感谢你的回复

**Comment by touchscale** [comment]
> 资源下载将会重构，并引入新的资源站
> 目前可以先去929275476下载资源包应急

请问入群验证的答案是

**Comment by qwerdvd** [comment]
百度就能出来
