### ISSUE TITLE
加载错误

### ISSUE THREAD

**Issue by C-Jun-GIT** [qwerdvd/StarRailUID#115]
![Image_1700410895463.png](https://github.com/qwerdvd/StarRailUID/assets/84917972/41ad6a73-27e9-43c5-bd9d-a266690ab1a6)
加载插件时发生错误无法加载

**Comment by KimigaiiWuyi** [comment]
poetry run pip install starrail_damage_cal

**Comment by C-Jun-GIT** [comment]
> `poetry run pip install starrail_damage_cal`
> 安装依赖即可

感谢！已解决
