### ISSUE TITLE
sr强制刷新以及查询错误

### ISSUE THREAD

**Issue by C-Jun-GIT** [qwerdvd/StarRailUID#118]
刷新的时候极大概率会出现这种错误
![图片](https://github.com/qwerdvd/StarRailUID/assets/84917972/06ffd20c-0b8d-4b0f-b4d2-846be1940a43)
有时刷新成功了，查询也会出错
![图片](https://github.com/qwerdvd/StarRailUID/assets/84917972/40466375-2535-4ea9-b764-56a3e321b55a)

**Comment by KimigaiiWuyi** [comment]
更新依赖即可
`poetry run pip install starrail_damage_cal -U`

**Comment by C-Jun-GIT** [comment]
> 更新依赖即可 `poetry run pip install starrail_damage_cal -U`

是在StarRailUID下更新依赖吗？
