### ISSUE TITLE
查询角色报错的解决方案

### ISSUE THREAD

**Issue by WaterEmissary** [qwerdvd/StarRailUID#25]
搞了2天终于装上了，然后发现除了查询角色别的功能都好用，一用查询角色就报这个错误
![1](https://github.com/qwerdvd/StarRailUID/assets/41639205/c5c2a80e-8d2d-4523-8399-914b3cb3c937)
问了一圈chatgpt后找到在报错那一段原码里加上一个.convert('RGBA')就可以了
![2](https://github.com/qwerdvd/StarRailUID/assets/41639205/0ddef7d0-9280-43be-894a-3e06ed730d42)
![3](https://github.com/qwerdvd/StarRailUID/assets/41639205/a9024c3b-bbd4-4178-af5a-a01b65c88cc6)

**Comment by qwerdvd** [comment]
pr welcome!
