### ISSUE TITLE
能添加一个ssl校验开关吗

### ISSUE THREAD

**Issue by yxkisane** [qwerdvd/StarRailUID#3]
请大佬弄一个ssl校验开关

**Comment by KimigaiiWuyi** [comment]
看下后台报错

**Comment by yxkisane** [comment]
> 看下后台报错

![9U~7@68ZGA 7 2AL{IE% A](https://user-images.githubusercontent.com/93441183/235872257-c504e7c8-5e2b-404a-99b4-22d6a1c230f3.png)

**Comment by KimigaiiWuyi** [comment]
core和插件全部更新
core更新： `gs全部更新`
插件更新： `core更新插件starrail`
然后该插件就会依照core的配置关闭ssl校验

**Comment by yxkisane** [comment]
> core和插件全部更新 core更新： `gs全部更新` 插件更新： `core更新插件starrail` 然后该插件就会依照core的配置关闭ssl校验

刚刚试过了，还是不行，重新拉取也一样

**Comment by KimigaiiWuyi** [comment]
> > core和插件全部更新 core更新： `gs全部更新` 插件更新： `core更新插件starrail` 然后该插件就会依照core的配置关闭ssl校验
> 
> 刚刚试过了，还是不行，重新拉取也一样

我看代码应该没有问题，确定starrailuid和core都是最新的，并且在网页控制台关闭**core的ssl校验**了吗

**Comment by yxkisane** [comment]
> > > core和插件全部更新 core更新： `gs全部更新` 插件更新： `core更新插件starrail` 然后该插件就会依照core的配置关闭ssl校验
> > 
> > 
> > 刚刚试过了，还是不行，重新拉取也一样
> 
> 我看代码应该没有问题，确定starrailuid和core都是最新的，并且在网页控制台关闭**core的ssl校验**了吗

我都更新过了，控制台也确定关闭了,还是不行
![~0O4P~`4TP@EJ9JP)DEBI K](https://user-images.githubusercontent.com/93441183/235913780-2a95eef3-ebed-4a52-aff7-d6ba3ec6ea48.png)

**Comment by qwerdvd** [comment]
如果解决了就关掉了，如果还有类似问题，请开个新的issue
