### ISSUE TITLE
查询角色时报错

### ISSUE THREAD

**Issue by grinxxoo** [qwerdvd/StarRailUID#34]
资源文件还是无法在更新是自动下载吗，我要怎么获取这些文件
报错如下:
nonebot_plugin_gocqhttp | [215562134] 收到好友 故人(1522575015) 的消息: #sr查询彦卿 (-51049053)
05-18 07:39:55 [SUCCESS] nonebot | OneBot V11 215562134 | [message.private.friend]: Message -51049053 from 1522575015 '#sr查询彦卿'
05-18 07:39:55 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
05-18 07:39:55 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot
05-18 07:39:55 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
05-18 07:39:55 [INFO] gsuid_core.handler | [Raw] raw_text=#sr查询彦卿, image=None, at=None, image_list=None, at_list=[], is_tome=True, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=215562134, msg_id=-51049053, user_type=direct, group_id=None, user_id=1522575015, user_pm=1, content=[Message(type='text', data='#sr查询彦卿')],  
05-18 07:39:55 [INFO] gsuid_core.handler | [Trigger] 消息 「sr查询彦卿」 触发 「prefix」 类型触发器, 关键词: 「sr查询」  
05-18 07:39:55 [INFO] gsuid_core.handler | [Command] command=sr查询, text=彦卿 
05-18 07:39:55 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
05-18 07:39:55 [INFO] GenshinUID | 开始执行[查询角色面板]
05-18 07:39:55 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
05-18 07:39:55 [INFO] GenshinUID | [查询角色面板]uid: 102291611
Task exception was never retrieved
future: <Task finished name='Task-1703' coro=<send_char_info() done, defined at /root/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_charinfo/__init__.py:23> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/root/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_charinfo/__init__.py", line 25, in send_char_info
    im = await _get_char_info(bot, ev, ev.text)
  File "/root/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_charinfo/__init__.py", line 59, in _get_char_info
    im = await draw_char_info_img(msg, uid, ev.image)
  File "/root/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_charinfo/draw_char_img.py", line 87, in draw_char_info_img
    Image.open(CHAR_PORTRAIT_PATH / f'{char.char_id}.png')
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/PIL/Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/root/gsuid_core/data/StarRailUID/resource/character_portrait/1209.png'

**Comment by WaterEmissary** [comment]
给机器人发这个命令
sr下载全部资源
