### ISSUE TITLE
所以…… 这个要怎么装？

### ISSUE THREAD

**Issue by fsqhn** [qwerdvd/StarRailUID#4]
GenshinUID是用的包管理器装的，就直接nb plugin install nonebot-plugin-genshinuid完事。
但这个并不能用包管理器装。
然后GenshinUID的手动装貌似是基于开发者模式的？说是
`进插件文件夹内，一般位于{Bot目录}/src/plugins下
输入安装命令（前提安装过git）
git clone -b v4-nonebot2 https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git --depth=1 --single-branch
使用命令cd GenshinUID进入插件文件夹
安装依赖pip install -r requirements.txt(如果你的Nonebot2运行在虚拟环境，需要进入虚拟环境安装依赖)
回到Bot目录下，使用命令nb run启动Bot`
然后我第一步就尬住了，我的bot目录下并没有src文件夹……  
明明看的确实是nonebot2的插件安装指导来着。

**Comment by wuchangjun233** [comment]
git clone于gscore的plugins目录
这个不是nb插件 是gscore插件
[gsuid_core](https://github.com/Genshin-bots/gsuid_core)

**Comment by KimigaiiWuyi** [comment]
仔细看[文档](https://docs.gsuid.gbots.work/#/)
如果已经成功安装gsuidcore并且能在控制台看到消息了
可以直接用`core安装插件starrail`这个命令安装
