### ISSUE TITLE
在sr每日签到时候，要不要加一个sruid的none判断吧？

### ISSUE THREAD

**Issue by mhy9989** [qwerdvd/StarRailUID#5]
有的只有原神，没有星轨，但是星轨一起签到sruid为none就会报错。以及只有星轨没有原神的，建议区分一下。

**Comment by qwerdvd** [comment]
https://github.com/qwerdvd/StarRailUID/commit/5ee926c16bdd969bcdfa97df64eab1b1139ab4c3
更新一下试试
