### ISSUE TITLE
大佬问一下支持yunzai 是怎么做的

### ISSUE THREAD

**Issue by Misakami** [qwerdvd/StarRailUID#50]
我看云崽bot核心没有对应的连接器啊

**Comment by KimigaiiWuyi** [comment]
文档没有补上，需要使用这个插件
https://gitee.com/xiaoye12123/ws-plugin

**Comment by Misakami** [comment]
大佬ws链接应该是多少 我填成这样不行gsuid,ws://127.0.0.1:8765/genshinuid,3,5,0

**Comment by xiaoye12123** [comment]
> 大佬ws链接应该是多少我填成这样不行gsuid,ws://127.0.0.1:8765/genshinuid,3,5,0
ws地址是ws://127.0.0.1:8765/ws/Yunzai

**Comment by Misakami** [comment]
> > 大佬ws链接应该是多少我填成这样不行gsuid,ws://127.0.0.1:8765/genshinuid,3,5,0
> > ws地址是ws://127.0.0.1:8765/ws/Yunzai

感谢大佬
