### ISSUE TITLE
提个bug，圣遗物数据有问题。

### ISSUE THREAD

**Issue by gaowenhao** [qwerdvd/StarRailUID#52]
StarRailUID/starrailuid_charinfo/to_data.py 文件 192行：

 relic_temp['Level'] = relic['Level'] if 'Level' in relic else 1

把结尾那个1改成0 ，遗器默认是0级的，代码中这样写会导致玩家的0级圣遗物主词条数据不对。

我这网不好，诸君自行修复一下吧

**Comment by qwerdvd** [comment]
fixed in https://github.com/qwerdvd/StarRailUID/commit/2582cd77a9916406d1419948226dcec2501e8b44
