### ISSUE TITLE
刷新和查询

### ISSUE THREAD

**Issue by yhzcake** [qwerdvd/StarRailUID#54]
今天突然强制刷新和查询不好用了,在尝试重启bot/更新core/更新sruid后
产生了如下报错

![image](https://github.com/qwerdvd/StarRailUID/assets/80627671/adaf8d70-6948-48fe-8fe0-4398dcaea75c)

下面是来自nb的日志
`05-29 14:00:05 [DEBUG] GenshinUID | [message.private.friend]: Message 417462310 from 1367808860 'sr强制刷新'
05-29 14:00:05 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot
05-29 14:00:05 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
05-29 14:00:05 [DEBUG] nonebot | Stop event propagation
05-29 14:00:05 [DEBUG] nonebot | Checking for matchers completed
05-29 14:00:05 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
05-29 14:00:05 [INFO] GenshinUID | [sr强制刷新]uid: 103592444
05-29 14:01:07 [INFO] nonebot_plugin_gocqhttp | [3580818212] 收到好友 刹帝利(1367808860) 的消息: sr查询希儿 (1877395632)
05-29 14:01:07 [SUCCESS] nonebot | OneBot V11 3580818212 | [message.private.friend]: Message 1877395632 from 1367808860 'sr查询希儿'
05-29 14:01:07 [DEBUG] nonebot | Running PreProcessors...
05-29 14:01:07 [DEBUG] nonebot | Checking for matchers in priority 1...
05-29 14:01:07 [DEBUG] nonebot | Checking for matchers in priority 999...
05-29 14:01:07 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
05-29 14:01:07 [DEBUG] nonebot | Running Matcher(type='message', module=GenshinUID)
05-29 14:01:07 [TRACE] nonebot | Matcher(type='message', module=GenshinUID) run with incoming args: bot=Bot(type='OneBot V11', self_id='3580818212'), event=PrivateMessageEvent(time=1685340067, self_id=3580818212, post_type='message', sub_type='friend', user_id=1367808860, message_type='private', message_id=1877395632, message=sr查询希儿, original_message=sr查询希儿, raw_message='sr查询希儿', font=0, sender=Sender(user_id=1367808860, nickname='刹帝利', sex='unknown', age=0, card=None, area=None, level=None, role=None, title=None), to_me=True, reply=None, target_id=3580818212), state={'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None, 'command_whitespace': None}}
05-29 14:01:07 [DEBUG] nonebot | Running handler Dependent(call=get_all_message)
05-29 14:01:07 [DEBUG] GenshinUID | [message.private.friend]: Message 1877395632 from 1367808860 'sr查询希儿'
05-29 14:01:07 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot
05-29 14:01:07 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
05-29 14:01:07 [DEBUG] nonebot | Stop event propagation
05-29 14:01:07 [DEBUG] nonebot | Checking for matchers completed
05-29 14:01:07 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
05-29 14:01:07 [INFO] GenshinUID | 开始执行[查询角色面板]
05-29 14:01:07 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
05-29 14:01:07 [INFO] GenshinUID | [查询角色面板]uid: 103592444`

下面是core的日志
`05-29 14:11:06 [INFO] gsuid_core.handler | [Raw] raw_text=sr强制刷新, image=None, at=None, image_list=None, at_list=[], is_tome=True, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=3580818212, msg_id=-10889951, user_type=direct, group_id=None, user_id=1367808860, user_pm=1, content=[Message(type='text', data='sr强制刷新')],  
05-29 14:11:06 [INFO] gsuid_core.handler | [Trigger] 消息 「sr强制刷新」 触发 「command」 类型触发器, 关键词: 「sr强制刷新」  
05-29 14:11:06 [INFO] gsuid_core.handler | [Command] command=sr强制刷新, text= 
05-29 14:11:35 [INFO] gsuid_core.handler | [Raw] raw_text=sr查询希儿, image=None, at=None, image_list=None, at_list=[], is_tome=True, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=3580818212, msg_id=-2007046729, user_type=direct, group_id=None, user_id=1367808860, user_pm=1, content=[Message(type='text', data='sr查询希儿')],  
05-29 14:11:35 [INFO] gsuid_core.handler | [Trigger] 消息 「sr查询希儿」 触发 「prefix」 类型触发器, 关键词: 「sr查询」  
05-29 14:11:35 [INFO] gsuid_core.handler | [Command] command=sr查询, text=希儿 
05-29 14:12:38 [INFO] gsuid_core.handler | [Raw] raw_text=sr强制刷新, image=None, at=None, image_list=None, at_list=[], is_tome=True, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=3580818212, msg_id=-1094464556, user_type=direct, group_id=None, user_id=1367808860, user_pm=1, content=[Message(type='text', data='sr强制刷新')],  
05-29 14:12:38 [INFO] gsuid_core.handler | [Trigger] 消息 「sr强制刷新」 触发 「command」 类型触发器, 关键词: 「sr强制刷新」  
05-29 14:12:38 [INFO] gsuid_core.handler | [Command] command=sr强制刷新, text= `

总之就是发送消息之后触发了但是不发送消息

**Comment by qwerdvd** [comment]
伤害计算部分修改了数据格式，请先使用 sr强制刷新 刷新保存信息

**Comment by yhzcake** [comment]
> 伤害计算部分修改了数据格式，请先使用 sr强制刷新 刷新保存信息

可是强制刷新刷新不出来啊
查询我知道了是修改了数据格式
但是强制刷新没有任何的反应
core显示收到消息并且触发了,但是没有刷新信息或者报错
什么反应都没有

**Comment by qwerdvd** [comment]
这是网络问题，请检查网络连接

**Comment by yhzcake** [comment]
> 这是网络问题，请检查网络连接

貌似是强制刷新卡在哪了然后其他的定时任务加进来把强制刷新给顶了,然后报的错
经常等十分钟什么反应也没有然后直到定时的信息出来就报错

**Comment by yhzcake** [comment]
`05-30 14:05:00 [SUCCESS] nonebot | OneBot V11 3580818212 | [message.group.normal]: Message -687490734 from 1367808860@[群:540973863] 'sr强制刷新'
05-30 14:05:00 [INFO] gsuid_core.handler | [Raw] raw_text=sr强制刷新, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=3580818212, msg_id=-687490734, user_type=group, group_id=540973863, user_id=1367808860, user_pm=1, content=[Message(type='text', data='sr强制刷新')],
05-30 14:05:00 [INFO] gsuid_core.handler | [Trigger] 消息 「sr强制刷新」 触发 「command」 类型触发器, 关键词: 「sr强制刷新」
05-30 14:05:00 [INFO] gsuid_core.handler | [Command] command=sr强制刷新, text=
05-30 14:10:00 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_ann | [原神公告] 定时任务: 原神公告查询..
05-30 14:10:00 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_ann | 没有群订阅, 取消获取数据
Task exception was never retrieved
future: <Task finished name='Task-4530' coro=<send_card_info() done, defined at D:\nonebot\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\__init__.py:64> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "D:\nonebot\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\__init__.py", line 70, in send_card_info
    im = await api_to_card(uid)
  File "D:\nonebot\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\to_card.py", line 33, in api_to_card
    char_data_list = await api_to_dict(uid, enka_data)
  File "D:\nonebot\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\to_data.py", line 54, in api_to_dict
    sr_data = await get_char_card_info(sr_uid)
  File "D:\nonebot\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\sruid_utils\api\mihomo\requests.py", line 16, in get_char_card_info
    return req.json()
  File "C:\Users\yhz_cake\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-HscqR8Pf-py3.10\lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
05-30 14:30:00 [DEBUG] gsuid_core.utils.api.mys.request | {'data': None, 'message': '', 'retcode': 1034}
05-30 14:30:00 [INFO] gsuid_core.utils.api.mys.request | [upass] 进入处理...
05-30 14:30:00 [DEBUG] gsuid_core.utils.api.mys.request | {'retcode': 0, 'message': 'OK', 'data': {'current_stamina': 180, 'max_stamina': 180, 'stamina_recover_time': 0, 'accepted_epedition_num': 4, 'total_expedition_num': 4, 'expeditions': [{'avatars': ['https://uploadstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_71679g/9227b901575d08d01618dabc6d0acb1c.png', 'https://uploadstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_71679g/8a51def0685ed38fe9e496c850c25fff.png'], 'status': 'Finished', 'remaining_time': 0, 'name': '毁灭者的覆灭'}, {'avatars': ['https://uploadstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_71679g/46f32148adae2d3155852478405282a6.png', 'https://uploadstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_71679g/b6f6144f590a6104c0b3d38ba4edb1b6.png'], 'status': 'Finished', 'remaining_time': 0, 'name': '火帝动炉销剑戟'}, {'avatars': ['https://uploadstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_71679g/fce6b8618839625f36ba9e4113f54b4f.png', 'https://uploadstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_71679g/e1a7870d06940e1f5f1f8b11f808664b.png'], 'status': 'Finished', 'remaining_time': 0, 'name': '无名之地 ，无名之人'}, {'avatars': ['https://uploadstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_71679g/e08bca34eccdbe30fb04eeedf656e343.png', 'https://uploadstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_71679g/53928b0f3048e536f93663aea51d2022.png'], 'status': 'Finished', 'remaining_time': 0, 'name': '阿卡夏记录'}]}}
05-30 14:30:00 [INFO] plugins.StarRailUID.StarRailUID.starrailuid_resin | [sr推送检查]完成!等待消息推送中...
05-30 14:30:00 [DEBUG] plugins.StarRailUID.StarRailUID.starrailuid_resin | {'onebot': {'direct': {'1367808860': '你的开拓力快满啦！\n可发送[srmr]或者[sr每日]来查看更多信息！\n'}, 'group': {}}}
05-30 14:30:00 [INFO] gsuid_core.bot | [发送消息to] onebot - direct - 1367808860
05-30 14:30:00 [DEBUG] gsuid_core.utils.api.mys.request | {'retcode': 0, 'message': 'OK', 'data': {'challenge': '3be5bf01be1318dcd7209edc87e63849', 'gt': '846fea0fd833b173bec7a25920851739', 'new_captcha': 1, 'success': 1}}
05-30 14:30:00 [DEBUG] gsuid_core.utils.api.mys.request | {'data': None, 'message': 'invalid request', 'retcode': -10001}
05-30 14:30:01 [INFO] plugins.StarRailUID.StarRailUID.starrailuid_resin | [sr推送检查] 私聊推送完成
05-30 14:30:01 [INFO] plugins.StarRailUID.StarRailUID.starrailuid_resin | [sr推送检查] 群聊推送完成
05-30 14:30:01 [DEBUG] gsuid_core.utils.api.mys.request | {'retcode': 0, 'message': 'OK', 'data': {'device_fp': '38d7eeaae1658', 'code': 200, 'msg': 'ok'}}
05-30 14:30:01 [ERROR] plugins.GenshinUID.GenshinUID.genshinuid_resin.notice | [推送提醒]获取106322135的数据失败!
05-30 14:30:01 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_resin | [推送检查]完成!等待消息推送中...
05-30 14:30:01 [DEBUG] plugins.GenshinUID.GenshinUID.genshinuid_resin | {}
127.0.0.1 - - [30/May/2023 14:34:38] "GET /?question=031496760099143 HTTP/1.1" 302 -
05-30 14:36:05 [SUCCESS] nonebot | OneBot V11 3580818212 | [message.group.normal]: Message 1309468904 from 1367808860@[群:540973863] 'sr强制刷新'
05-30 14:36:05 [INFO] gsuid_core.handler | [Raw] raw_text=sr强制刷新, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=3580818212, msg_id=1309468904, user_type=group, group_id=540973863, user_id=1367808860, user_pm=1, content=[Message(type='text', data='sr强制刷新')],
05-30 14:36:05 [INFO] gsuid_core.handler | [Trigger] 消息 「sr强制刷新」 触发 「command」 类型触发器, 关键词: 「sr强制刷新」
05-30 14:36:05 [INFO] gsuid_core.handler | [Command] command=sr强制刷新, text=
Task exception was never retrieved
future: <Task finished name='Task-4774' coro=<send_card_info() done, defined at D:\nonebot\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\__init__.py:64> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "D:\nonebot\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\__init__.py", line 70, in send_card_info
    im = await api_to_card(uid)
  File "D:\nonebot\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\to_card.py", line 33, in api_to_card
    char_data_list = await api_to_dict(uid, enka_data)
  File "D:\nonebot\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\to_data.py", line 54, in api_to_dict
    sr_data = await get_char_card_info(sr_uid)
  File "D:\nonebot\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\sruid_utils\api\mihomo\requests.py", line 16, in get_char_card_info
    return req.json()
  File "C:\Users\yhz_cake\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-HscqR8Pf-py3.10\lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
05-30 15:00:00 [DEBUG] gsuid_core.utils.api.mys.request | {'data': None, 'message': '', 'retcode': 1034}
05-30 15:00:00 [INFO] gsuid_core.utils.api.mys.request | [upass] 进入处理...
05-30 15:00:00 [DEBUG] gsuid_core.utils.api.mys.request | {'data': None, 'message': 'invalid request', 'retcode': -10001}
05-30 15:00:00 [DEBUG] gsuid_core.utils.api.mys.request | {'retcode': 0, 'message': 'OK', 'data': {'device_fp': '38d7eeaae9b70', 'code': 200, 'msg': 'ok'}}
05-30 15:00:00 [DEBUG] gsuid_core.utils.api.mys.request | {'retcode': 0, 'message': 'OK', 'data': {'challenge': 'c6dc9109a8f75b4dd4d6be38e3159c27', 'gt': '846fea0fd833b173bec7a25920851739', 'new_captcha': 1, 'success': 1}}
05-30 15:00:00 [DEBUG] gsuid_core.utils.api.mys.request | {'data': None, 'message': 'invalid request', 'retcode': -10001}
05-30 15:00:00 [DEBUG] gsuid_core.utils.api.mys.request | {'data': None, 'message': 'invalid request', 'retcode': -10001}
05-30 15:00:01 [DEBUG] gsuid_core.utils.api.mys.request | {'retcode': 0, 'message': 'OK', 'data': {'device_fp': '38d7eeaae9b76', 'code': 200, 'msg': 'ok'}}
05-30 15:00:01 [ERROR] plugins.StarRailUID.StarRailUID.starrailuid_resin.notice | [sr推送提醒]获取103592444的数据失败!
05-30 15:00:01 [INFO] plugins.StarRailUID.StarRailUID.starrailuid_resin | [sr推送检查]完成!等待消息推送中...
05-30 15:00:01 [DEBUG] plugins.StarRailUID.StarRailUID.starrailuid_resin | {}
05-30 15:00:01 [DEBUG] gsuid_core.utils.api.mys.request | {'retcode': 0, 'message': 'OK', 'data': {'device_fp': '38d7eeaae9b78', 'code': 200, 'msg': 'ok'}}
05-30 15:00:01 [ERROR] plugins.GenshinUID.GenshinUID.genshinuid_resin.notice | [推送提醒]获取106322135的数据失败!
05-30 15:00:01 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_resin | [推送检查]完成!等待消息推送中...
05-30 15:00:01 [DEBUG] plugins.GenshinUID.GenshinUID.genshinuid_resin | {}`

**Comment by qwerdvd** [comment]
`"C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
网络问题，请检查网络连接
