### ISSUE TITLE
查询抽卡记录找不到资源文件

### ISSUE THREAD

**Issue by wuhaoyu1993** [qwerdvd/StarRailUID#8]
资源文件没有自动下载，找不到资源文件
查询抽卡记录报错，FileNotFoundError
![图片](https://github.com/qwerdvd/StarRailUID/assets/29732990/bed1b37d-cc0c-4c65-9d53-a78cc9bd2f17)
看了一下gsuid_core/data/StarRailUID/resource文件夹里面都没有图片
这个因该是在启动的时候下载的吧？重启也没有见到下载

**Comment by wuhaoyu1993** [comment]
![图片](https://github.com/qwerdvd/StarRailUID/assets/29732990/24577208-b8b0-49c8-9ff1-156b0f5cae85)
和这个有关系吗

**Comment by KimigaiiWuyi** [comment]
sruid目前还处于wip阶段，资源包需要自己放
可以看群文件

**Comment by grinxxoo** [comment]
> sruid目前还处于wip阶段，资源包需要自己放
> 可以看群文件
> 或者下载[该仓库](https://github.com/P1482/StarRail-Gamefilecollection)的内容

那么怎么入群
